### PR TITLE
test1 Jupyter notebook pull request

### PR DESCRIPTION
**Pull request by bboscoe**

### CODE REVIEW

**Comment by bboscoe** [comment]
Tuan, (just thought of this) a good method is to have the group create
"issues" in the github repo if they have any questions, that way everyone
can see and share them, good collab communication, good practices.

**Comment by followthesheep** [comment]
You mean use issue tracking like a forum? I guess that could work. Do we
leave the all the issues open?

**Comment by bboscoe** [comment]
ummm, don't we close them when resolved and then refer to them if people
have the same error?

**Comment by followthesheep** [comment]
When the issues is closed, it doesn't show up automatically in the issues
page. You have to look at the closed issues. I guess as long as we are
clear about the procedure, people can probably figure it out.

**Comment by bboscoe** [comment]
Food for thought. Agree, they have to look through closed issues...

**Pull request merged**
